apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsql-config
data:
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
